### ISSUE TITLE
java.lang.NoSuchMethodError, scala 2.11.4, processors 5.3

### ISSUE THREAD

**Issue by versusvoid** [sistanlp/processors#27]
Basic app:
```scala
object Main extends App {

  val proc:Processor = new CoreNLPProcessor(withDiscourse = true)

  // the actual work is done here
  val doc = proc.annotate("John Smith went to China. He visited Beijing, on January 10th, 2013.")

}
```
fails with:
```
Adding annotator tokenize
Adding annotator ssplit

Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.0 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [2.4 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [2.8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [1.7 sec].
Initializing JollyDayHoliday for sutime with classpath:edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
Aug 06, 2015 5:53:50 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: null
Aug 06, 2015 5:53:50 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: temporal-composite-8:ranges
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.8 sec].
Exception in thread "main" java.lang.NoSuchMethodError: edu.stanford.nlp.trees.TreebankLanguagePack.punctuationWordRejectFilter()Ljava/util/function/Predicate;
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.mkGSF(CoreNLPProcessor.scala:49)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.gsf$lzycompute(CoreNLPProcessor.scala:39)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.gsf(CoreNLPProcessor.scala:39)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor$$anonfun$parse$1.apply(CoreNLPProcessor.scala:70)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor$$anonfun$parse$1.apply(CoreNLPProcessor.scala:65)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.parse(CoreNLPProcessor.scala:65)
	at edu.arizona.sista.processors.Processor$class.annotate(Processor.scala:73)
	at edu.arizona.sista.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:23)
	at edu.arizona.sista.processors.Processor$class.annotate(Processor.scala:56)
	at edu.arizona.sista.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:23)
	at Main$.delayedEndpoint$Main$1(Main.scala:13)
	at Main$delayedInit$body.apply(Main.scala:8)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(Main.scala:8)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

build.sbt:
```sbt
name := "Test"

version := "1.0"

scalaVersion := "2.11.4"

scalacOptions += "-feature"

libraryDependencies ++= Seq(
  "edu.arizona.sista" %% "processors" % "5.3",
  "edu.arizona.sista" %% "processors" % "5.3" classifier "models"
)

libraryDependencies += "com.github.javaparser" % "javaparser-core" % "2.1.0"
```

Tried to redownload models in case they were corrupted - no luck.

**Comment by MihaiSurdeanu** [comment]
Hi,
This code works when it is part of processors. I suspect that, for some reason I don't really understand, your code uses an incorrect version of Stanford CoreNLP. Can you please make sure you use 3.5.1? Maybe trying clearing your .ivy2 cache to see what version is downloaded?
Thanks,
Mihai

**Comment by versusvoid** [comment]
Oh, stupid me, separate old 3.4 jar was lying on classpath along with 3.5.1 from ivy.
Thanks a lot :smiley:
